### PR TITLE
change: use bootstrap Card component

### PR DESCRIPTION
**Pull request by 0xB10C**
Bootstrap 5 offers a card component with e.g. default paddings,
borders, and rounded corners, which can be used in the "Technology"
section.

https://getbootstrap.com/docs/5.0/components/card/

### CODE REVIEW

**Comment by 0xB10C** [comment]
before:

image

after:

image

**Comment by 0xB10C** [comment]
also:

https://twitter.com/RCasatta/status/1413038101275021314

:)

**Comment by 0xB10C** [comment]
ping @rustyrussell in case you missed this :)

**Comment by rustyrussell** [comment]
Thanks!  I know nothing...

**Pull request merged**
